models/Car.php
<?php

namespace app\models;
/**
 * This is the model class for table "car".
 *
 * @property int $id
 * @property int $car_modification_id
 * @property int $year
 *
 * @property CarModification $carModification
 *
 * @property int $car_brand
 * @property [] carBrandAndType
 *
 * @property string brand
 * @property string type
 * @property string modification
 * @property string fullTitle
 */
class Car extends \yii\db\ActiveRecord
{

    public $car_brand;
    public $car_type;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['car_modification_id', 'year'], 'required'],
            [['car_modification_id', 'year'], 'integer'],
            [['car_modification_id', 'year'], 'unique', 'targetAttribute' => ['car_modification_id', 'year']],
            [['car_modification_id'], 'exist', 'skipOnError' => true, 'targetClass' => CarModification::className(), 'targetAttribute' => ['car_modification_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'car_modification_id' => 'Car Modification ID',
            'year' => 'Year',
            'car_brand' => 'Car Brand',
            'car_type' => 'Car Type',
        ];
    }

    /**
     * @return string
     */
    public function getBrand()
    {
        return $this->carModification->carType->carBrand->title;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->carModification->carType->title;
    }

    /**
     * @return string
     */
    public function getModification()
    {
        return $this->carModification->title;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarModification()
    {
        return $this->hasOne(CarModification::className(), ['id' => 'car_modification_id']);
    }

    public function getFullTitle(){
        return  $this->brand . ' ' . $this->type. ' ' . $this->modification;
    }

    /**
     * @return array
     */
    public function getCarBrandAndType(){
        $result = [];
        $carBrands = CarBrand::find()
            ->with(['carTypes','carModifications'])
            ->all();
        foreach ($carBrands as $brands){
            $result['store'][$brands->id]['title']= $brands->title;
            foreach ($brands->carTypes as $type){
                $result['store'][$brands->id]['types'][$type->id] = $type->title;

                foreach ($type->carModifications as $modification){
                    $result['store'][$brands->id]['modification'][$type->id][$modification->id] = $modification->title;
                }
            }
        }

        if ($this->car_modification_id){
            $result['id_type'] = $this->carModification->car_type_id;
            $result['id_brand'] = $this->carModification->carType->car_brand_id;
            $result['id_modification'] = $this->car_modification_id;
        } else {
            $result['id_type'] = 1;
            $result['id_brand'] = 1;
            $result['id_modification'] = 0;
        }
        return $result;
    }

    /**
     * @param $year
     * @return Car
     */
    public static function createNew($year)
    {
        $car = new self();
        $car->year = $year;
        return $car;
    }
}

models/CarType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "car_type".
 *
 * @property int $id
 * @property int $car_brand_id
 * @property string $title
 *
 * @property CarModification[] $carModifications
 * @property CarBrand $carBrand
 */
class CarType extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['car_brand_id'], 'required'],
            [['car_brand_id'], 'integer'],
            [['title'], 'string', 'max' => 55],
            [['car_brand_id', 'title'], 'unique', 'targetAttribute' => ['car_brand_id', 'title']],
            [['car_brand_id'], 'exist', 'skipOnError' => true, 'targetClass' => CarBrand::className(), 'targetAttribute' => ['car_brand_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'car_brand_id' => 'Car Brand ID',
            'title' => 'Type',
        ];
    }

    /**
     * @return string
     */
    public function getBrand()
    {
        return $this->carBrand->title;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarModifications()
    {
        return $this->hasMany(CarModification::className(), ['car_type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarBrand()
    {
        return $this->hasOne(CarBrand::className(), ['id' => 'car_brand_id']);
    }

    /**
     * @param $title
     * @return CarType
     */
    public static function createNew($title)
    {
        $carType = new self();
        $carType->title = $title;
        return $carType;
    }
}

controllers/CarController.php
<?php

namespace app\controllers;

use app\forms\CarCleanForm;
use app\services\CarService;
use Yii;
use app\models\Car;
use app\models\search\CarSearch as CarSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CarController implements the CRUD actions for Car model.
 */
class CarController extends Controller
{
    private $carService;

    public function __construct($id, $module, CarService $carService, $config = [])
    {
        $this->carService = $carService;
        parent::__construct($id, $module, $config = []);
    }



    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Car models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Car model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * New Car model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNew()
    {
        $form = new CarCleanForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            $car = $this->carService->createNew($form);
            Yii::$app->session->setFlash('success', 'New car has been created.');
            return $this->redirect(['view', 'id' => $car->id]);
        }

        return $this->render('car-new', [
            'carCleanForm' => $form,
        ]);
    }

    /**
     * New Car model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $car = new Car;
        if ($car->load(Yii::$app->request->post()) && $car->save()) {
            Yii::$app->session->setFlash('success', 'Add new car.');
            return $this->redirect(['view', 'id' => $car->id]);
        }

        return $this->render('create', [
            'model' => $car,
        ]);
    }

    /**
     * Updates an existing Car model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Car model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    /**
     * Finds the Car model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Car the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Car::find()
                ->where(['car.id' => $id])->joinWith([
                    'carModification',
                    'carModification.carType',
                    'carModification.carType.carBrand'
                ])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

controllers/CarModificationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CarModification;
use app\models\search\CarModificationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CarModificationController implements the CRUD actions for CarModification model.
 */
class CarModificationController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CarModification models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarModificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CarModification model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CarModification model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CarModification();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CarModification model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing CarModification model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CarModification model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CarModification the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CarModification::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/CarTypeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CarType;
use app\models\search\CarTypeSearch as CarTypeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CarTypeController implements the CRUD actions for CarType model.
 */
class CarTypeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CarType models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarTypeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CarType model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CarType model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CarType();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CarType model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing CarType model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CarType model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CarType the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CarType::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/car/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Car */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="car-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'class' =>'carCreate'
         ]
    ]); ?>



    <?= $form->field($model, 'car_brand')->dropDownList(["{{brand.title}}"],
        ['v-model' => 'id_brand',
            'options' => [
                [
                    'v-for' => '(brand, id_brand) in brands["store"]',
                    'v-bind:value' => 'id_brand'
                ]
            ]]) ?>
    <div v-bind:class="{ carCreate__error: !hasType }">
        <?= $form->field($model, 'car_type')->dropDownList(["{{type}}"],
            ['v-model' => 'id_type', 'v-if' => 'hasType', 'options' => [
                [
                    'v-for' => '(type, id_type) in valueBrand.types',
                    'v-bind:value' => 'id_type'
                ]
            ]]); ?>
        <div v-if="!hasType">
            This brand does not have any type.
            <?= Html::a('Add type', Url::to(['car-type/create'])); ?>
        </div>
    </div>
    <div v-bind:class="{ carCreate__error: !hasModification }">
        <?= $form->field($model, 'car_modification_id')->dropDownList(["{{modification}}"],
            ['v-model' => 'id_modification', 'v-if' => 'hasModification', 'options' => [
                [
                    'v-for' => '(modification, id_modification) in valueBrand.modification[id_type]',
                    'v-bind:value' => 'id_modification'
                ]
            ]]); ?>
        <div v-if="!hasModification">
            This type does not have any modifications.
            <?= Html::a('Add modification', Url::to(['car-modification/create'])); ?>
        </div>
    </div>

    <?= $form->field($model, 'year',
        ['options' => ['v-if' => 'hasType']])->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success', ':disabled' => '!hasModification']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <script type="text/javascript">
        var data = <?= json_encode($model->getCarBrandAndType(), JSON_FORCE_OBJECT) ?>;
    </script>
</div>

views/car/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CarSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="car-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'car_type_id') ?>

    <?= $form->field($model, 'year') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/car/car-new.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $carCleanForm app\forms\CarCleanForm */
/* @var $form yii\widgets\ActiveForm */
/* @var $this yii\web\View */
/* @var $model app\models\Car */

$this->title = 'Create New Car';
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="new-car-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="car-brand-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($carCleanForm, 'brand')->textInput(['maxlength' => true]) ?>

        <?= $form->field($carCleanForm, 'type')->textInput(['maxlength' => true]) ?>

        <?= $form->field($carCleanForm, 'modification')->textInput(['maxlength' => true]) ?>

        <?= $form->field($carCleanForm, 'year')->textInput(['maxlength' => true]) ?>


        <div class="form-group">
            <?= Html::submitButton('Create', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/car/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Car */

$this->title = 'Create Car';
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/car/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CarSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cars';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Car', ['create'], ['class' => 'btn btn-success']) ?>

        <?= Html::a('Create New Car', ['new'], ['class' => 'btn btn-primary']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'brand',
            'type',
            'modification',
            'year',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/car/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Car */

$this->title = 'Update Car: ' . $model->fullTitle;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="car-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/car/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Car */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cars', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="car-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [

            'brand',
            'type',
            'modification',
            'year',
        ],
    ]) ?>

</div>